const FETCH_COUNTRIES = Symbol("FETCH_COUNTRIES");
const FETCH_COUNTRIES_SUCCESS = Symbol("FETCH_COUNTRIES_SUCCESS");
const FETCH_COUNTRIES_FAIL = Symbol("FETCH_COUNTRIES_FAIL");
const ADD_POPULATION = Symbol("ADD_POPULATION");
const DELETE_POPULATION = Symbol("DELETE_POPULATION");

export default {
    FETCH_COUNTRIES,
    FETCH_COUNTRIES_SUCCESS,
    FETCH_COUNTRIES_FAIL,
    ADD_POPULATION,
    DELETE_POPULATION
};
