export const COUNTRY_DATA_CREATE = 'COUNTRY_DATA_CREATE'
export const COUNTRY_DATA_READ = 'COUNTRY_DATA_READ'
export const COUNTRY_DATA_UPDATE = 'COUNTRY_DATA_UPDATE'
export const COUNTRY_DATA_DELETE = 'COUNTRY_DATA_DELETE'