export const GET_DATA = "GET_DATA";
export const CHANGE_COUNTRY = "CHANGE_COUNTRY";
export const CHANGE_POPULATION = "CHANGE_POPULATION";
export const UPDATE_POPULATION = "UPDATE_POPULATION";
export const DELETE_POPULATION = "DELETE_POPULATION";
export const ERR_PARSING = "ERR_PARSING";
