import { NAME } from './constants';

export const GET_COUNTRIES_REQUEST = `${NAME}/GET_COUNTRIES_REQUEST`;
export const GET_COUNTRIES_SUCCESS = `${NAME}/GET_COUNTRIES_SUCCESS`;
export const GET_COUNTRIES_ERROR = `${NAME}/GET_COUNTRIES_ERROR`;

export const SET_COUNTRY_POPULATION = `${NAME}/SET_COUNTRY_POPULATION`;
export const DELETE_COUNTRY_POPULATION = `${NAME}/DELETE_COUNTRY_POPULATION`;
